apiVersion: apps/v1
kind: DeamonSet
metadata:
  namespace: argocd-dep
  name: argocd-deamonset
  labels:
    env: test
spec:
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      labels:
        env: test
    spec:
      containers:
        - name: nginx
          image: nginx
