apiVersion: v1
kind: Service
metadata:
  namespace: argocd-dep
  name: dep-service
  labels:
    env: test
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    env: test
