apiVersion: v1
kind: Secret
metadata:
  namespace: argocd-demo
  name: argocd-secret
data:
  username: YWRtaW4=
  password: YWRtaW4=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: argocd-demo
  name: argocd-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      labels:
        env: test
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: mount-sc
              mountPath: "/husain-mount"
              readOnly: true
      volumes:
        - name: mount-sc
          secret:
            secretName: argocd-secret
            
---
apiVersion: v1
kind: Service
metadata:
  namespace: argocd-demo
  name: argocd-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    env: test
